### PR TITLE
[FIX] cannot-filter-comments | Comment-type questions now update its …

### PR DESCRIPTION
**Pull request by radoeska-v**
…values as responses get filtered interactively.

Problem:
I noticed that one of the features of survey-analytics "Interactive filtering for the select type questions" was not filtering the comment-type questions as well. Ther data was correctly updated as the filter applied but changes were not rendered on the screen. 

Solution:
When an update of the visualizer's data should be done, in the `AlternativeVisualizersWrapper.ts` I applied the same procedure implemented in the `SelectBase.ts`. That is: destroying the content of the HTML node and rendering the node with the updated content.
The fix applies for both display modes: Wordcloud and Texts in table.

How to test:
1. Use a Survey with select type questions and comment type questions.
2. Render the responses using the VisualizationPanel.
3. Select one bar to interactively filter responses.
4. Make sure that only comments belonging to the filtered responses are shown and not all of them.

### CODE REVIEW

**Comment by tsv2013** [comment]
The product is under massive development/refactoring right now. Thank you for the PR, but could you check the latest version please?

**Comment by radoeska-v** [comment]
Yes, I've checked. The bug exists in the latest version. The function where I made the update is changed 10 months ago, according to the git blame. Can you check why the build is failing? I don't have access to the build pipeline on Azure.

**Comment by tsv2013** [comment]
@radoeska-v could you please create an issue here and we'll fix it as soon as finished with data providing functionality?

**Comment by radoeska-v** [comment]
Sure

**Comment by tsv2013** [comment]
Thank you, @radoeska-v

**Comment by dmitrykurmanov** [comment]
the [issue](https://github.com/surveyjs/survey-analytics/issues/58)

**Pull request closed without merging**
